### ISSUE TITLE
As a developer or team lead, I want to update approach grid with keyboard in order to speed up updates

### ISSUE THREAD

**Issue by yoda888** [agilist-ai/Neelix-for-Jira-Cloud#1]
It would be faster to toggle timeline stamping with a space key press. User would use left and right keys to navigate and press space to toggle the timeline stamp on/off.

**Comment by agilist-ai** [comment]
Thank you. Agreed - this is a useful feature. Will implement.

**Comment by agilist-ai** [comment]
Released in 2.1
