### ISSUE TITLE
Opposite visualization order of planned versus actual in different views

### ISSUE THREAD

**Issue by rfajta** [agilist-ai/Neelix-for-Jira-Cloud#5]
**Is your feature request related to a problem? Please describe.**
On the planning view and on the widget on a single card the _planned_ (blue squares) and actual (green squares) execution are in the opposite order.

**Describe the solution you'd like**
Make the order to _planned_ and _actual_ on the widget, so it will be consistently visualized in Neelix.

**Comment by agilist-ai** [comment]
Fixed in https://github.com/agilist-ai/Neelix-for-Jira-Cloud/releases/tag/2.3.2
